CREATE TABLE ACCIONES (
    Id INT PRIMARY KEY IDENTITY,
    Accion NVARCHAR(50) NOT NULL
);

CREATE TABLE ESTADOS (
    Id INT PRIMARY KEY IDENTITY,
    Estado NVARCHAR(50) NOT NULL
);

CREATE TABLE GENEROS (
    Id INT PRIMARY KEY IDENTITY,
    Genero NVARCHAR(50) NOT NULL,
    Abreviacion NVARCHAR(5) NOT NULL
);

CREATE TABLE ROLES (
    Id INT PRIMARY KEY IDENTITY,
    Rol NVARCHAR(50) NOT NULL
);

CREATE TABLE TIPOSDOCUMENTO (
    Id INT PRIMARY KEY IDENTITY,
    TipoDocumento NVARCHAR(50) NOT NULL,
    Abreviacion NVARCHAR(5) NOT NULL
);

CREATE TABLE Logs (
    Id INT PRIMARY KEY IDENTITY,
    IdAccion INT NOT NULL,
    Descripcion NVARCHAR(50) NOT NULL,
    DateLog DATETIME NOT NULL,
    FOREIGN KEY (IdAccion) REFERENCES ACCIONES(Id)
);

CREATE TABLE USUARIOS (
    Id INT PRIMARY KEY IDENTITY,
    PrimerNombre NVARCHAR(50) NOT NULL,
    SegundoNombre NVARCHAR(50) NOT NULL,
    PrimerApellido NVARCHAR(50) NOT NULL,
    SegundoApellido NVARCHAR(50),
    IdTipoDocumento INT NOT NULL,
    NumeroDocumento NVARCHAR(50) NOT NULL,
    IdGenero INT NOT NULL,
    Telefono NVARCHAR(50) NOT NULL,
    Correo NVARCHAR(50) NOT NULL,
    Contraseña NVARCHAR(50) NOT NULL,
    IdRol INT NOT NULL,
    IdEstado INT NOT NULL,
    FOREIGN KEY (IdTipoDocumento) REFERENCES TIPOSDOCUMENTO(Id),
    FOREIGN KEY (IdGenero) REFERENCES GENEROS(Id),
    FOREIGN KEY (IdRol) REFERENCES ROLES(Id),
    FOREIGN KEY (IdEstado) REFERENCES ESTADOS(Id)
);
CREATE TABLE SOPORTES (
    Id INT PRIMARY KEY IDENTITY,
    Asunto NVARCHAR(255) NOT NULL,
    Descripcion NVARCHAR(MAX) NOT NULL,
    IdUsuario INT NOT NULL,
    Fecha DATETIME NOT NULL,
    IdEstado INT NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(Id),
    FOREIGN KEY (IdEstado) REFERENCES Estados(Id)
);