CREATE TABLE Logs (
    Id INT PRIMARY KEY IDENTITY,
    IdAccion INT NOT NULL,
    Descripcion NVARCHAR(MAX) NOT NULL,
    DateLog DATETIME NOT NULL,
    FOREIGN KEY (IdAccion) REFERENCES ACCIONES(Id)
);
ALTER TABLE dbo.Logs
ALTER COLUMN Descripcion NVARCHAR(MAX);